image: node:22

stages:
  - deploy

cache:
  paths:
    - .pnpm-store/

deploy:
  stage: deploy
  before_script:
    - npm install -g pnpm
    - pnpm config set store-dir .pnpm-store
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
  script:
    - pnpm install
    - pnpm build
    - pnpm run publish --no-git-checks
  only:
    - release

