image: node:22

stages:
  - install
  - lint
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/
    - .pnpm-store/

before_script:
  - npm install -g pnpm
  - pnpm config set store-dir .pnpm-store

install:
  stage: install
  script:
    - pnpm install
  artifacts:
    paths:
      - node_modules/
      - .pnpm-store/
    expire_in: 1 hour

lint:
  stage: lint
  script:
    - pnpm lint
  dependencies:
    - install

test:
  stage: test
  script:
    - pnpm test
  coverage: '/Lines\s*:\s*(\d+\.?\d*)%/'
  dependencies:
    - install

build:
  stage: build
  script:
    - pnpm build
  artifacts:
    paths:
      - packages/*/lib/
    expire_in: 1 week
  dependencies:
    - install

deploy:
  stage: deploy
  script:
    - pnpm publish
  only:
    - main
  dependencies:
    - build
    - test
    - lint
