image: node:20

stages:
  - install
  - lint
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/
    - packages/*/node_modules/

install:
  stage: install
  script:
    - pnpm install
    - npx lerna bootstrap
  artifacts:
    paths:
      - node_modules/
      - packages/*/node_modules/
    expire_in: 1 hour

lint:
  stage: lint
  script:
    - npx lerna run lint
  dependencies:
    - install

test:
  stage: test
  script:
    - npx lerna run test
  coverage: '/Lines\s*:\s*(\d+\.?\d*)%/'
  dependencies:
    - install

build:
  stage: build
  script:
    - npx lerna run build
  artifacts:
    paths:
      - packages/*/lib/
      - packages/*/dist/
    expire_in: 1 week
  dependencies:
    - install

deploy:
  stage: deploy
  script:
    - npx lerna publish --yes
  only:
    - main
  dependencies:
    - build
    - test
    - lint
