name: Checks (Local server)

on:
  push:
    branches: [ main, dev ]
    paths: 
      - 'packages/**'
  pull_request:
    branches: [ main, dev ]
    paths: 
      - 'packages/**'
  workflow_dispatch:



jobs:
  test:
    if: github.actor == 'RastGame'
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Set pnpm store directory
        run: pnpm config set store-dir ~/.pnpm-store

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm run build

      - name: Run tests
        run: pnpm run test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}