name: Spellcheck
on:
  pull_request:
    branches: [main, dev]
    paths:
      - '**/*.md'
      - '**/*.mdx'
    
  push:
    branches: [main, dev]
    paths:
      - '**/*.md'
      - '**/*.mdx'

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run spellcheck
        uses: rojopolis/spellcheck-github-actions@0.33.0
        with:
          config_path: .github/spellcheck-config.yml
          task_name: Markdown
