name: Spellcheck Action Check
on:
  pull_request:
    branches: [ main, dev ]
    paths:
      - '**/*.md'
      - '**/*.mdx'
    
  push:
    branches: [ main, dev ]
    paths:
      - '**/*.md'
      - '**/*.mdx'



jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: rojopolis/spellcheck-github-actions@0.51.0
      name: Spellcheck
      continue-on-error: true
      id: spellcheck
    - name: Format spellcheck results
      if: steps.spellcheck.outcome == 'failure'
      run: |
        echo "Formatting spellcheck results..."
        pyspelling -c spellcheck.yaml 2>&1 | node scripts/format-spellcheck.js || true
